### PR TITLE
Improve the default download path.

### PR DESCRIPTION
**Pull request by vext01**
Hi,

Found gemini and ncgopher today. Neat!

Currently ncgopher defaults the download path to `$CWD/Downloads` and if this path doesn't exist, we get a crash:

```
thread '<unnamed>' panicked at 'Unable to open file 'Downloads/img.jpg'', src/controller.rs:762:37
```

This confused me.

So this change makes things more user friendly by:
 a) Selecting either ~/Downloads or /tmp as the default download path.
 b) Creating the path if it doesn't exist.

### CODE REVIEW

**Comment by vext01** [comment]
By the way, How do I use an external image viewer? I have one configured in settings, just I don't know how to invoke it from the UI.

**Comment by jansc** [comment]
Thanks for pinning down this issue and providing a fix! Looks good to me.

Regarding the external image viewer, it seems like you have found yet another bug. I'm on vacation right now with a rather unstable internet line, but I will try to fix that as soon as I'm back home again. Thanks, again, for your help!

**Comment by vext01** [comment]
> Regarding the external image viewer, it seems like you have found yet another bug.

I see. I can try and track it down if I find time.

> Thanks, again, for your help!

No worries. And thanks for ncgopher!

**Comment by jansc** [comment]
I did some more investigation yesterday and it seems that this feature simply disappeared in a refactoring a while ago. In it's current state, it won't function: the image viewer is called with the URL of the image. The right way is, of course, to download the image to a temporary file and then call the image viewer.

**Pull request merged**
